name: Deploy to GitHub Pages
on:
  push:
    branches:
    - master
  workflow_dispatch:
permissions: {}
jobs:
  pages-configuration:
    name: Pages configuration
    permissions:
      pages: read
    runs-on: ubuntu-24.04
    outputs:
      pages: ${{ steps.get-configuration.outputs.pages }}
    steps:
    - id: get-configuration
      name: Get configuration
      run: |
        response_file=$(mktemp)
        trap 'rm "${response_file}"' EXIT
        status_code=$(
          curl --header "Accept: application/vnd.github+json" \
            --header "Authorization: token ${GITHUB_TOKEN}" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --output "${response_file}" --silent --write-out "%{http_code}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/pages"
        )
        case "${status_code}" in
          200)
            pages_json=$(jq -c '.' "${response_file}")
            printf "GitHub Pages configuration: %s\n" "${pages_json}"
            build_type=$(jq -r '.build_type' "${response_file}")
            if [ ! "${build_type}" = "workflow" ]; then
              printf "GitHub Pages source must be set to GitHub Actions.\n" >&2
              exit 1
            fi
            printf "pages=%s\n" "${pages_json}" >>"${GITHUB_OUTPUT:?}"
            ;;
          404)
            printf "GitHub Pages is disabled.\n"
            printf "To enable GitHub Pages, visit the repository settings.\n"
            ;;
          *)
            printf "Unknown GitHub API status code '%s'.\n" "${status_code}" >&2
            exit 1
        esac
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
  build:
    name: Build
    permissions:
      contents: read
    needs: pages-configuration
    if: ${{ needs.pages-configuration.outputs.pages }}
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
      env:
        BASE_URL:
          ${{ fromJSON(needs.pages-configuration.outputs.pages).html_url }}
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
  deploy:
    name: Deploy
    permissions:
      id-token: write
      pages: write
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4
